[package]
name = "jointed-bridge"
version = "0.1.1"
authors = ["Frédéric Hamidi <frederic.hamidi@gmail.com>"]
edition = "2018"

[dependencies]
piston-app = { path = "../../piston-app" }
wrapped2d = "0.4.0"

