[package]
name = "perlin-noise-2d"
version = "2.0.0"
authors = ["Frédéric Hamidi <frederic.hamidi@gmail.com>"]

[dependencies]
gfx = "*"
gfx_device_gl = "*"
piston-app = { path = "../../piston-app" }

