[package]
name = "piston-app"
version = "1.4.0"
authors = ["Frédéric Hamidi <frederic.hamidi@gmail.com>"]

[dependencies]
fnv = "*"
fps_counter = "*"
noise = "*"
piston_window = "*"
pistoncore-sdl2_window = "*"
rand = "*"
vecmath = "*"

